website/app/urls.py
from django.urls import path
from app.views import(
	
	create_app_view,
	detail_app_view,
	edit_app_view,
)

app_name = 'app'

urlpatterns = [
	path('create/', create_app_view, name="create"),
	path('<slug>/', detail_app_view, name="detail"),
	path('<slug>/edit', edit_app_view, name="edit"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from myapp.views import (
    home_screen_view,
)

#from app.views import (
#    create_app_view,
#)
from account.views import (
    registration_view,
    logout_view,
    login_view, 
    account_view,
    must_authenticate_view,
)
 

    

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('app/', include('app.urls', 'app')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
   
   
    #path('account/', include('django.contrib.auth.urls')),

    #Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),

         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/app/templates/app/snippets/app_post_pagination.html
  <!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
<nav aria-label="Page navigation">
<ul class="pagination pg-grey justify-content-center">
	{% if app_posts.has_previous %}
        <li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}
		  page={{ app_posts.previous_page_number }}">&laquo; Previous</a>
		</li>
    {% endif %}

	{% for i in app_posts.paginator.page_range %}
		{% if app_posts.number == i %}
			<li class="page-item active"><a class="page-link">{{ i }}</a></li>
		{% else %}
			<li class="page-item" ><a class="page-link" href="?{% if query %}q={{query}}&{% endif %}
			page={{ i }}">{{ i }}</a></li>
		{% endif %}
	{% endfor %}
    
    {% if app_posts.has_next %}
    	<li class="page-item">
		  <a class="page-link" href="?{% if query %}q={{query}}&{% endif %}page={{ app_posts.next_page_number }}">Next</a>
		</li>
		<li class="page-item">
		  <a class="page-link"  href="?{% if query %}q={{query}}&{% endif %}page={{ app_posts.paginator.num_pages }}">Last &raquo;</a>
		</li>
    {% endif %}
</ul>
</nav>
</div>
<!-- end pagination-->

website/app/templates/app/snippets/app_post_snippet.html
<style type="text/css">
	.card{
		max-width: 700px;
		width: 100%;
	}
	.card-body{
		padding: 20px;
		
	}
</style>

{% if app_post %}
<div class="container">
	<div class="row">
		<!-- Blog Post -->
		<div class="card m-auto">
			<a href="{% url 'app:detail' post.slug %}">
				<img class="card-img-top" src="{{app_post.image.url}}">
			</a>
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'app:detail' post.slug %}">
					<h2 class="card-title">{{app_post.title}}</h2>
				</a>
				<p class="card-text">{{app_post.body|safe|truncatechars:180}}</p>
				<p>
					{% if app_post.author == request.user %}
						<a href="{% url 'app:edit' app_post.slug %}" class="btn btn-primary">Update</a>
					{% endif %}
			    </p>
			</div>
			<div class="card-footer text-muted">
			  Updated on {{app_post.date_updated}} by {{app_post.author}}
			</div>
		</div>
	</div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title">No results</h2>
				<p class="card-text">There were no results matching the search: "{{query}}"</p>
			</div>
		</div>
	</div>
</div>

{% endif %}