website/app/urls.py
from django.urls import path
from app.views import(
	
	create_app_view,
	detail_app_view,
	edit_app_view,
)

app_name = 'app'

urlpatterns = [
	path('create/', create_app_view, name="create"),
	path('<slug>/', detail_app_view, name="detail"),
	path('<slug>/edit', edit_app_view, name="edit"),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from myapp.views import (
    home_screen_view,
)

#from app.views import (
#    create_app_view,
#)
from account.views import (
    registration_view,
    logout_view,
    login_view, 
    account_view,
    must_authenticate_view,
)
 

    

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('app/', include('app.urls', 'app')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
   
   
    #path('account/', include('django.contrib.auth.urls')),

    #Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),

         name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/myapp/models.py
from django.db import models

# Create your models here.

#PRIORITY = [
#("H", "high"),
#("M", "medium"),
#("L", "low"),
#]


#class Question(models.Model):
#	title					= models.CharField(max_length=60)
#	Question 				= models.TextField(max_length=400)
#	priority				= models.CharField(max_length=1, choices=PRIORITY)

	
#	def __str__(self):
#		return self.title

#	class Meta:
#		verbose_name = "The Question"
#		verbose_name_plural = "People Question"

website/myapp/views.py
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
#from account.models import Account
from app.views import get_app_queryset
from app.models import AppPost

# Create your views here.

APP_POSTS_PER_PAGE = 1

def home_screen_view(request):
	
	
	context = {}

	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)


	app_posts = sorted(get_app_queryset(query), key=attrgetter('date_updated'), reverse=True)
	context['app_posts'] = app_posts


	#context['some_string'] = "variable passing to views"
	#context['some_number'] = 123

	#context =  {
	#'some_string': "variable passing to views",
	#'some_number': 123
	#}

	#list_of_values = []
	#list_of_values.append("1st entry")
	#list_of_values.append("2nd entry")
	#list_of_values.append("3rd entry")
	#list_of_values.append("4th entry")
	#context['list_of_values'] = list_of_values
 	
	#accounts = Account.objects.all()
	#context['accounts'] = accounts


	#pagination
	page = request.GET.get('page',1)
	app_posts_paginator = Paginator(app_posts, APP_POSTS_PER_PAGE)

	try:
		app_posts = app_posts_paginator.page(page)
	except PageNotAnInteger:
		app_posts = app_posts_paginator.page(APP_POSTS_PER_PAGE)
	except EmptyPage:	
		app_posts = app_posts_paginator.page(app_posts_paginator.num_pages)

	context['app_posts'] = app_posts


	return render(request, "myapp/home.html", context)

	

website/myapp/templates/myapp/home.html
{% extends 'base.html' %}


{% block content %}

{% load static %}

<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.app-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}

	
</style>

<div class="d-flex flex-column pb-2">
	<img  class="img-fluid mx-auto d-block"  src="{% static 'tables.jpg' %}" alt="gayathri project" width="auto" height="20%">
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Restraunt Table Booking</h1>
	<p  class="lead"><b>A table reservation is an arrangement made in advance to have a table available at a restaurant. While most restaurants in the vast majority of the world do not require a reservation, and some do not have a policy or simply any channel for making one, so-called higher-end restaurants mainly in overcrowded cities often require a reservation, and some may have tables booked for weeks in advance. At particularly exclusive venues, it may be impossible to make a reservation on the same day as the planned visit.</b></p>
</div>

<!-- main content -->
<div class="container">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'tables.jpg' %}" width="72" height="72">
					<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
	  					framework and you'll see why in this course.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'app:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if app_posts %}
				{% for post in app_posts %}
					<div class="app-post-container">
						{% include 'app/snippets/app_post_snippet.html' with app_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="app-post-container">
					{% include 'app/snippets/app_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->

		<!-- Pagination -->
		{% include 'app/snippets/app_post_pagination.html' with app_posts=app_posts %}

		</div>
		<!-- end blog feed -->



		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<img class="img-fluid d-block m-auto pb-2" src="{% static 'tables.jpg' %}" width="72" height="72">
				<p class="lead">In this course you'll learn how to build a simple blog with user registration and blog CRUD functionality. Django is a powerful 
  					framework and you'll see why in this course.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'app:create' %}">Create post</a></p>
			</div>
		
		</div>
		<!-- end Right 'create post' column  -->

		

	</div>
</div>
{% endblock content %}

<!--
	
<div class="d-flex flex-column pb-2">
	<img  class="img-fluid mx-auto d-block"  src="{% static 'tables.jpg' %}" alt="gayathri project" width="150%" height="20%">
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
	<h1 class="display-4">Restraunt Table Booking</h1>
	<p  class="lead"><b>A table reservation is an arrangement made in advance to have a table available at a restaurant. While most restaurants in the vast majority of the world do not require a reservation, and some do not have a policy or simply any channel for making one, so-called higher-end restaurants mainly in overcrowded cities often require a reservation, and some may have tables booked for weeks in advance. At particularly exclusive venues, it may be impossible to make a reservation on the same day as the planned visit.</b></p>
</div>-->



<!--<div class="container">

	<div class="row">
	<div class="d.flex flex-column">
		<h4> Registered users</h4>
		{% for account in accounts %}
	 	<p>{{account}}</p>
		{% endfor %}-->
	
	<!-- right create postcolumn
		<div class="create-post-bar d-lg-none col-lg-7 offset-lg-1" style="border:1px solid #000;">
			<a href="{% url 'app:create'%}">createpost</a>	

		</div>

	end postcolymn
	 blog post
		<div class="left-column col-lg-7 offset-lg-1" style="border:1px solid #000;">
			<div class="blog-post-container">
				<p>things</p>
			</div>

			<div class="blog-post-container">
				<p>things</p>
			</div>
				
			<div class="blog-post-container">
				<p>things</p>
			</div>
				
			<div class="blog-post-container">
				<p>things</p>
			</div>					
		</div>

	end blog

	 right create postcolumn
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column" style="border:1px solid #000;">
			<div class="create-post-bar">
				<p>me</p>
				<p>me</p>
				<p>me</p>
				<p>me</p>
				<a href="{% url 'app:create'%}">createpost</a>
			</div>	
		</div>

	



	</div>	
</div>-->